### ISSUE TITLE
CLI Tool initial roadmap

### ISSUE THREAD

**Issue by arves100** [arves100/LibLyketo#3]
The CLI tool should provide all access for everything that LibLyketo provides.
Currently, the tool just decrypts a CryptedObject (MCOZ) and it should be adapter to support more and more functionality.

List of funtionality missing:
- [ ] Basic Proto pack and unpack (Perhaps export and import RAW just for test?)
- [ ] Basic EterPack pack and unpack
- [ ] Configuration of Proto FourCC and XTEA keys, as well as the type of CryptedObject to use during packing.
- [ ] Configuring EterPack XTEA keys (when Type2 will be supported), extensions (easy to do), version, FourCC and the type of algorithm to use to crypt the Index file (MCOZ/MCSP).
- [ ] Automatic append "d:/" to ymir work, or let the user specify "d_".
